/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    city002_Cube001_1: THREE.Mesh;
    city002_Cube001_2: THREE.Mesh;
    city002_Cube001_3: THREE.Mesh;
    city002_Cube001_4: THREE.Mesh;
    city002_Cube001_5: THREE.Mesh;
    city002_Cube001_6: THREE.Mesh;
    city002_Cube001_7: THREE.Mesh;
    city002_Cube001_8: THREE.Mesh;
    city002_Cube001_9: THREE.Mesh;
    city002_Cube001_10: THREE.Mesh;
    city002_Cube001_11: THREE.Mesh;
    city002_Cube001_12: THREE.Mesh;
    city002_Cube001_13: THREE.Mesh;
    city002_Cube001_14: THREE.Mesh;
    city002_Cube001_15: THREE.Mesh;
    city002_Cube001_16: THREE.Mesh;
    city002_Cube001_17: THREE.Mesh;
    city002_Cube001_18: THREE.Mesh;
    city002_Cube001_19: THREE.Mesh;
    city002_Cube001_20: THREE.Mesh;
    city002_Cube001_21: THREE.Mesh;
    city002_Cube001_22: THREE.Mesh;
    city002_Cube001_23: THREE.Mesh;
    city002_Cube001_24: THREE.Mesh;
    city002_Cube001_25: THREE.Mesh;
    city002_Cube001_26: THREE.Mesh;
    city002_Cube001_27: THREE.Mesh;
    city002_Cube001_28: THREE.Mesh;
    city002_Cube001_29: THREE.Mesh;
    city002_Cube001_30: THREE.Mesh;
    city002_Cube001_31: THREE.Mesh;
    city002_Cube001_32: THREE.Mesh;
    Cube001_Cube004_1: THREE.Mesh;
    Cube001_Cube004_2: THREE.Mesh;
    Cube001_Cube004_3: THREE.Mesh;
  };
  materials: {
    wall1_brick: THREE.MeshPhysicalMaterial;
    ["wall1_brick_wall1_brick.png"]: THREE.MeshPhysicalMaterial;
    ["wall1_brick_wall1_brick2.png"]: THREE.MeshPhysicalMaterial;
    wall1_brick_NONE: THREE.MeshPhysicalMaterial;
    wall1_panel: THREE.MeshPhysicalMaterial;
    ["wall1_panel_wall1_ceiling.png"]: THREE.MeshPhysicalMaterial;
    ["wall1_panel_wall1_panel.png"]: THREE.MeshPhysicalMaterial;
    ["wall1_panel_wall1_brick2.png"]: THREE.MeshPhysicalMaterial;
    wall1_panel_NONE: THREE.MeshPhysicalMaterial;
    wall1_brick2: THREE.MeshPhysicalMaterial;
    ["wall1_brick2_wall1_brick2.png"]: THREE.MeshPhysicalMaterial;
    wall1_flatdark: THREE.MeshPhysicalMaterial;
    wall1_door: THREE.MeshPhysicalMaterial;
    ["wall1_door_wall1_panel.png"]: THREE.MeshPhysicalMaterial;
    wall1_ceiling: THREE.MeshPhysicalMaterial;
    wall1_top: THREE.MeshPhysicalMaterial;
    sign2: THREE.MeshPhysicalMaterial;
    sign1: THREE.MeshPhysicalMaterial;
    Potato_Box: THREE.MeshPhysicalMaterial;
    roadside: THREE.MeshPhysicalMaterial;
    road: THREE.MeshPhysicalMaterial;
    brick2: THREE.MeshPhysicalMaterial;
    ["brick2_brick2.png"]: THREE.MeshPhysicalMaterial;
    ["brick2_brick2_mid.png"]: THREE.MeshPhysicalMaterial;
    ["brick2_brickwobbly0.png"]: THREE.MeshPhysicalMaterial;
    ["brick2_wall1_brick.png"]: THREE.MeshPhysicalMaterial;
    brick2_mid: THREE.MeshPhysicalMaterial;
    ["brick2_mid_brick2_mid.png"]: THREE.MeshPhysicalMaterial;
    ["brick2_mid_wall1_brick.png"]: THREE.MeshPhysicalMaterial;
    brick2_mid_NONE: THREE.MeshPhysicalMaterial;
    brick_flat_light: THREE.MeshPhysicalMaterial;
    window2: THREE.MeshPhysicalMaterial;
    sky_sides: THREE.MeshStandardMaterial;
    sky_up: THREE.MeshStandardMaterial;
    sky_down: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/8bit.gltf") as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_1.geometry}
          material={materials.wall1_brick}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_2.geometry}
          material={materials["wall1_brick_wall1_brick.png"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_3.geometry}
          material={materials["wall1_brick_wall1_brick2.png"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_4.geometry}
          material={materials.wall1_brick_NONE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_5.geometry}
          material={materials.wall1_panel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_6.geometry}
          material={materials["wall1_panel_wall1_ceiling.png"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_7.geometry}
          material={materials["wall1_panel_wall1_panel.png"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_8.geometry}
          material={materials["wall1_panel_wall1_brick2.png"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_9.geometry}
          material={materials.wall1_panel_NONE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_10.geometry}
          material={materials.wall1_brick2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_11.geometry}
          material={materials["wall1_brick2_wall1_brick2.png"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_12.geometry}
          material={materials.wall1_flatdark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_13.geometry}
          material={materials.wall1_door}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_14.geometry}
          material={materials["wall1_door_wall1_panel.png"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_15.geometry}
          material={materials.wall1_ceiling}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_16.geometry}
          material={materials.wall1_top}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_17.geometry}
          material={materials.sign2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_18.geometry}
          material={materials.sign1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_19.geometry}
          material={materials.Potato_Box}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_20.geometry}
          material={materials.roadside}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_21.geometry}
          material={materials.road}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_22.geometry}
          material={materials.brick2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_23.geometry}
          material={materials["brick2_brick2.png"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_24.geometry}
          material={materials["brick2_brick2_mid.png"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_25.geometry}
          material={materials["brick2_brickwobbly0.png"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_26.geometry}
          material={materials["brick2_wall1_brick.png"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_27.geometry}
          material={materials.brick2_mid}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_28.geometry}
          material={materials["brick2_mid_brick2_mid.png"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_29.geometry}
          material={materials["brick2_mid_wall1_brick.png"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_30.geometry}
          material={materials.brick2_mid_NONE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_31.geometry}
          material={materials.brick_flat_light}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.city002_Cube001_32.geometry}
          material={materials.window2}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Cube004_1.geometry}
          material={materials.sky_sides}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Cube004_2.geometry}
          material={materials.sky_up}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Cube004_3.geometry}
          material={materials.sky_down}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/8bit.gltf");
